services:
    app:
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            target: local
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/app/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/app/apache-laravel.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - ${DOCKER_APP_PORT:-80}:80
        depends_on:
            - db

    db:
        platform: linux/amd64
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DOCKER_DB_PORT:-3306}:3306
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/init:/docker-entrypoint-initdb.d

volumes:
    db_data:
